version: '3.8'

services:
  server:
    image: myapp-back
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3003:3001
    env_file:
      - variables.env
    container_name: myapp-back
  app:
    image: myapp-front
    # No need for volumes for static front prod build
    ports:
      - 3000:3000
    container_name: myapp-front
