version: '3.8'

services:
  server:
    image: myapp-back-dev
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 3003:3001
    env_file:
      - variables.env
    container_name: myapp-back-dev
  app:
    image: myapp-front-dev
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 3000:3000
    container_name: myapp-front-dev
