services:
  app:
    image: hello-front-dev
    build:
      context: ./todo-frontend # The context will pick the todo-frontend directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend:/usr/src/app # The path can be relative
    ports:
      - 3000:3000
    container_name: hello-front-dev-2 # This will name the container hello-front-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-2
    depends_on:
      - app # wait for the frontend container to be started
